# Generated by Django 5.2.1 on 2025-05-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=150)),
                ('date', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField()),
                ('prio', models.BooleanField()),
                ('worked', models.CharField(max_length=100)),
            ],
        ),
    ]
