# Generated by Django 5.2.1 on 2025-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_alter_tasks_deadline_alter_tasks_prio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='prio',
            field=models.CharField(help_text="please use: 'critical', 'high', 'medium' or 'low'", max_length=10),
        ),
    ]
