# Generated by Django 5.2.1 on 2025-06-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_remove_boards_ticket_count_boards_tasks_to_do_count'),
        ('tasks_app', '0003_alter_tasks_options_alter_tasks_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards_app.boards'),
            preserve_default=False,
        ),
    ]
