# Generated by Django 5.2.1 on 2025-06-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_tasks_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('to-do', 'To Do'), ('in-progress', 'In Progress'), ('reviewing', 'Reviewing'), ('done', 'Done')], default='to-do', max_length=20),
        ),
    ]
