# Generated by Django 5.2.1 on 2025-06-03 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_tasks_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User, dem dieser Task zugewiesen ist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
