# Generated by Django 5.2.1 on 2025-06-03 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_alter_tasks_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='worked',
        ),
        migrations.AddField(
            model_name='tasks',
            name='worked',
            field=models.ManyToManyField(blank=True, help_text='User, die an diesem Task gearbeitet haben', related_name='worked_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
