# Generated by Django 5.2.1 on 2025-06-05 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0013_alter_tasks_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='deadline',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='prio',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='worked',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasks',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
