# Generated by Django 5.2.1 on 2025-06-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('member_count', models.FloatField(verbose_name='memeber')),
                ('ticket_count', models.FloatField(verbose_name='ticket')),
                ('tasks_to_do_count', models.FloatField(verbose_name='ticket')),
                ('tasks_high_prio_count', models.FloatField(verbose_name='ticket')),
                ('owner_id', models.FloatField(verbose_name='ticket')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
    ]
