# Generated by Django 5.2.1 on 2025-06-02 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='boards',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boards',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='tasks_high_prio_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='tasks_to_do_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='ticket_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boards',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
