# Generated by Django 5.2.1 on 2025-06-02 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_remove_boards_owner_id_boards_owner_and_more'),
        ('tasks_app', '0003_alter_tasks_options_alter_tasks_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='tasks_to_do_count',
        ),
        migrations.AddField(
            model_name='boards',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='boards',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='boards',
            name='ticket_count',
        ),
        migrations.AddField(
            model_name='boards',
            name='member_count',
            field=models.ManyToManyField(related_name='boards_member_count', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boards',
            name='ticket_count',
            field=models.ManyToManyField(to='tasks_app.tasks'),
        ),
    ]
