# Generated by Django 5.2.1 on 2025-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_remove_boards_tasks_high_prio_count_and_more'),
        ('tasks_app', '0003_alter_tasks_options_alter_tasks_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='ticket_count',
        ),
        migrations.AddField(
            model_name='boards',
            name='tasks_to_do_count',
            field=models.ManyToManyField(related_name='boards_with_this_task', to='tasks_app.tasks'),
        ),
    ]
