# Generated by Django 5.2.1 on 2025-06-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_remove_boards_ticket_count_boards_tasks_to_do_count'),
        ('tasks_app', '0005_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='tasks_to_do_count',
            field=models.ManyToManyField(limit_choices_to={'status': 'to-do'}, related_name='boards_with_this_task', to='tasks_app.tasks'),
        ),
    ]
