# Generated by Django 5.2.1 on 2025-06-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0006_remove_boards_tasks_to_do_count'),
        ('tasks_app', '0011_remove_tasks_assigned_to_alter_tasks_worked'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='tasks_to_do',
            field=models.ManyToManyField(limit_choices_to={'status': 'to-do'}, related_name='boards_with_this_task', to='tasks_app.tasks'),
        ),
    ]
