# Generated by Django 5.2.1 on 2025-06-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0008_remove_boards_member_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='tasks_to_do',
        ),
    ]
